import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import { Archetype } from '../../types/quiz';

// Register Inter font
Font.register({
  family: 'Inter',
  src: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2'
});

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontFamily: 'Inter'
  },
  header: {
    marginBottom: 30,
  },
  title: {
    fontSize: 24,
    marginBottom: 10,
    color: '#6c5ce7'
  },
  tagline: {
    fontSize: 16,
    marginBottom: 20,
    fontStyle: 'italic',
    color: '#fd79a8'
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    marginBottom: 10,
    color: '#6c5ce7'
  },
  text: {
    fontSize: 12,
    marginBottom: 10,
    lineHeight: 1.5
  },
  list: {
    marginLeft: 20,
  },
  listItem: {
    fontSize: 12,
    marginBottom: 5,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 10,
    color: '#666'
  }
});

interface LoveBlueprintProps {
  archetype: Archetype;
}

const LoveBlueprint = ({ archetype }: LoveBlueprintProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Your Romantic Archetype: {archetype.name}</Text>
        <Text style={styles.tagline}>"{archetype.tagline}"</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Core Characteristics</Text>
        <Text style={styles.text}>{archetype.description}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Compatibility Analysis</Text>
        <Text style={styles.text}>
          You are most compatible with: {archetype.compatibleWith.join(', ')}
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Communication Style</Text>
        <Text style={styles.text}>
          As a {archetype.name}, your communication approach is characterized by depth and nuance. You excel at:
        </Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Expressing emotions with clarity and authenticity</Text>
          <Text style={styles.listItem}>• Active listening and emotional validation</Text>
          <Text style={styles.listItem}>• Creating safe spaces for vulnerable conversations</Text>
          <Text style={styles.listItem}>• Reading between the lines in conversations</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Growth Opportunities</Text>
        <Text style={styles.text}>
          While your romantic nature brings many strengths, here are areas where conscious growth can enhance your relationships:
        </Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Balancing emotional depth with practical needs</Text>
          <Text style={styles.listItem}>• Managing expectations in relationships</Text>
          <Text style={styles.listItem}>• Setting healthy boundaries while maintaining connection</Text>
          <Text style={styles.listItem}>• Embracing imperfection in relationships</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Relationship Dynamics</Text>
        <Text style={styles.text}>Your ideal relationship dynamic includes:</Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Deep emotional intimacy and understanding</Text>
          <Text style={styles.listItem}>• Shared values and life philosophy</Text>
          <Text style={styles.listItem}>• Regular meaningful conversations</Text>
          <Text style={styles.listItem}>• Mutual growth and support</Text>
        </View>
      </View>

      <Text style={styles.footer}>
        Generated by Affinity AI - Your guide to deeper connections
      </Text>
    </Page>
  </Document>
);

export default LoveBlueprint;