import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.4
  },
  coverPage: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '90%',
    backgroundColor: '#f8f9ff'
  },
  coverTitle: {
    fontSize: 28,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 20,
    color: '#6c5ce7'
  },
  coverSubtitle: {
    fontSize: 18,
    marginBottom: 40,
    color: '#6c5ce7'
  },
  coverArchetypeName: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 20,
    color: '#fd79a8'
  },
  coverTagline: {
    fontSize: 14,
    fontStyle: 'italic',
    marginBottom: 40,
    color: '#6c5ce7'
  },
  section: {
    marginBottom: 15
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 8,
    color: '#6c5ce7'
  },
  text: {
    fontSize: 10,
    marginBottom: 8,
    lineHeight: 1.4
  },
  list: {
    marginLeft: 15
  },
  listItem: {
    fontSize: 10,
    marginBottom: 4
  },
  highlight: {
    backgroundColor: '#f8f9ff',
    padding: 8,
    marginBottom: 10,
    borderLeft: '3px solid #6c5ce7'
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 8,
    color: '#666'
  },
  watermark: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    fontSize: 60,
    color: 'rgba(108, 92, 231, 0.07)',
    fontFamily: 'Helvetica-Bold'
  }
});

const SampleLoveBlueprint = () => (
  <Document>
    {/* Cover Page */}
    <Page size="A4" style={styles.page}>
      <View style={styles.coverPage}>
        <Text style={styles.coverTitle}>Love Blueprint</Text>
        <Text style={styles.coverSubtitle}>Your Relationship Profile</Text>
        <Text style={styles.coverArchetypeName}>Narrative Idealist</Text>
        <Text style={styles.coverTagline}>"Love is a story I want to co-write."</Text>
        <Text style={{ fontSize: 14, color: '#666', marginTop: 40 }}>SAMPLE REPORT</Text>
      </View>
      <Text style={styles.watermark}>SAMPLE</Text>
    </Page>

    {/* Page 1: Archetype Overview */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Your Archetype: Narrative Idealist</Text>
        <Text style={styles.text}>
          As a Narrative Idealist, you experience love as a profound story that unfolds over time. You seek meaning in your connections and value emotional depth over casual encounters. Your romantic nature is characterized by a deep appreciation for the poetry of everyday moments and a desire to create lasting, meaningful bonds.
        </Text>
        
        <View style={styles.highlight}>
          <Text style={[styles.text, { fontFamily: 'Helvetica-Bold' }]}>
            Core Insight: You don't just fall in love—you craft love stories that become the foundation of your identity.
          </Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Your Romantic Strengths</Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Deep emotional intelligence and empathy</Text>
          <Text style={styles.listItem}>• Ability to see beauty and meaning in small moments</Text>
          <Text style={styles.listItem}>• Strong commitment to authentic connection</Text>
          <Text style={styles.listItem}>• Natural storytelling ability that enriches relationships</Text>
          <Text style={styles.listItem}>• Capacity for profound emotional intimacy</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Growth Opportunities</Text>
        <Text style={styles.text}>
          While your romantic idealism is a beautiful gift, it can sometimes create challenges:
        </Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Balancing emotional depth with practical relationship needs</Text>
          <Text style={styles.listItem}>• Managing expectations when reality doesn't match your romantic vision</Text>
          <Text style={styles.listItem}>• Learning to appreciate imperfect but genuine connections</Text>
          <Text style={styles.listItem}>• Developing resilience when relationships face mundane challenges</Text>
        </View>
      </View>

      <Text style={styles.footer}>
        Sample Report - Generated by Affinity AI
      </Text>
      <Text style={styles.watermark}>SAMPLE</Text>
    </Page>

    {/* Page 2: Communication Style */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Your Communication Style</Text>
        <Text style={styles.text}>
          As a Narrative Idealist, your communication is rich with emotion and meaning. You excel at expressing complex feelings and creating emotional safety for your partner.
        </Text>
        
        <Text style={[styles.text, { fontFamily: 'Helvetica-Bold', marginTop: 15 }]}>
          Strengths in Communication:
        </Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Expressing emotions with poetic clarity</Text>
          <Text style={styles.listItem}>• Active listening with genuine empathy</Text>
          <Text style={styles.listItem}>• Creating safe spaces for vulnerable conversations</Text>
          <Text style={styles.listItem}>• Reading between the lines and understanding subtext</Text>
          <Text style={styles.listItem}>• Sharing personal stories that deepen intimacy</Text>
        </View>

        <Text style={[styles.text, { fontFamily: 'Helvetica-Bold', marginTop: 15 }]}>
          Areas for Growth:
        </Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• Being direct about practical needs and concerns</Text>
          <Text style={styles.listItem}>• Discussing mundane topics without losing interest</Text>
          <Text style={styles.listItem}>• Addressing conflicts before they become dramatic</Text>
          <Text style={styles.listItem}>• Balancing emotional expression with logical problem-solving</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Conversation Starters for Deeper Connection</Text>
        <Text style={styles.text}>
          These prompts are designed specifically for your Narrative Idealist nature:
        </Text>
        <View style={styles.list}>
          <Text style={styles.listItem}>• "What's a moment from your childhood that still influences how you love?"</Text>
          <Text style={styles.listItem}>• "If our relationship were a book, what would this chapter be about?"</Text>
          <Text style={styles.listItem}>• "What's something beautiful you noticed about us this week?"</Text>
          <Text style={styles.listItem}>• "How do you imagine we'll look back on this time in our lives?"</Text>
          <Text style={styles.listItem}>• "What's a dream you have for us that you haven't shared yet?"</Text>
        </View>
      </View>

      <Text style={styles.footer}>
        Sample Report - Page 2 of 8
      </Text>
      <Text style={styles.watermark}>SAMPLE</Text>
    </Page>

    {/* Page 3: Compatibility Analysis */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Compatibility Analysis</Text>
        <Text style={styles.text}>
          Understanding how you connect with different personality types can help you build stronger relationships and recognize potential challenges early.
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: '#2d8f47' }]}>Highly Compatible: Vibrant Explorer</Text>
        <Text style={styles.text}>
          Vibrant Explorers bring excitement and spontaneity that can balance your depth with adventure. They appreciate your emotional intelligence while encouraging you to embrace new experiences.
        </Text>
        <View style={styles.highlight}>
          <Text style={styles.text}>
            <Text style={{ fontFamily: 'Helvetica-Bold' }}>Why it works:</Text> They help you live in the moment while you help them find deeper meaning in their adventures.
          </Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={[styles.sectionTitle, { color: '#2d8f47' }]}>Highly Compatible: Steady Guardian</Text>
        <Text style={styles.text}>
          Steady Guardians provide the security and consistency that allows your romantic nature to flourish. They appreciate your emotional depth and offer grounding when your idealism needs practical support.
        </Text>
        <View style={styles.highlight}>
          <Text style={styles.text}>
            <Text style={{ fontFamily: 'Helvetica-Bold' }}>Why it works:</Text> They create a safe foundation for your love stories to unfold naturally.
          </Text>
        </View>
      </View>

      <Text style={styles.footer}>
        Sample Report - Page 3 of 8
      </Text>
      <Text style={styles.watermark}>SAMPLE</Text>
    </Page>
  </Document>
);

export default SampleLoveBlueprint;