[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

